version: '3.0'

services:
    lnk_nginx:
        image: nginx:latest
        container_name: lnk_nginx
        ports:
            - 80:80
        depends_on:
            - lnk_php
        volumes:
            - .:/app/:cached
            - ./infra/etc/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            default:
                aliases:
                    - lnk.local

    lnk_php:
        build: ./infra/docker/php
        container_name: lnk_php
        working_dir: /app
        depends_on:
            - lnk_db
        volumes:
            - .:/app/:cached
            - ./infra/docker/volumes/php/composer:/root/.composer:cached

    lnk_db:
        image: mariadb:10.3.7
        ports:
            - 3306:3306
        volumes:
            - lnk-datavolume:/var/lib/mariadb
        container_name: lnk_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lnk
            MYSQL_USER: lnk
            MYSQL_PASSWORD: password

    lnk_composer:
        container_name: lnk_composer
        image: composer:latest
        command: install
        volumes:
            - .:/app/
volumes:
    lnk-datavolume:
