#!/bin/sh

PROJECT=$1;

echo "Setting up $PROJECT ..."

git clone git@github.com:john-needham/laravel-setup.git .

TEMPLATE="__PROJECT__"

# remove setup script from laravel-setup, we dont need it
rm ./setup

sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./docker-compose.yml
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./Makefile
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./infra/etc/nginx/site.conf
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./cmd

make build
make project tmp=tmp
shopt -s dotglob
mv ./tmp/* ./
rm ./tmp
make run

echo "## setup-sctipt-project: ${PROJECT}"  | sudo tee -a /etc/hosts
echo "127.0.0.1 ${PROJECT}.local" | sudo tee -a /etc/hosts
echo "## setup-sctipt-project-end" | sudo tee -a /etc/hosts
echo "" | sudo tee -a /etc/hosts

echo "Browse to http://${PROJECT}.local"
