#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "No project name supplied."
fi

PROJECT=$1;

if [ -d "./$PROJECT" ]; then
    echo "Folder exists already [$PROJECT]."
    exit;
fi

echo "Setting up $PROJECT ..."

KEY="laravel-setup-script-project: ${PROJECT}"

mkdir ${PROJECT}
cd ${PROJECT}

git clone git@github.com:john-needham/laravel-setup.git .

TEMPLATE="__PROJECT__"

# remove setup script from laravel-setup, we dont need it
rm ./setup

sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./docker-compose.yml
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./Makefile
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./infra/etc/nginx/site.conf
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" ./cmd

make build
make project tmp=tmp
shopt -s dotglob
mv ./tmp/* ./
rm ./tmp
make run

if grep -q "$KEY" /etc/hosts
then
    echo "Host file already configured"
else
    echo "## laravel-setup-script-project: ${PROJECT}"  | sudo tee -a /etc/hosts
    echo "127.0.0.1 ${PROJECT}.local" | sudo tee -a /etc/hosts
    echo "## laravel-setup-script" | sudo tee -a /etc/hosts
    echo "" | sudo tee -a /etc/hosts
fi

echo "Browse to http://${PROJECT}.local"
