#!/bin/sh

if [ $# -eq 0 ]
  then
    echo "No project name supplied."
fi

DIR_PATH=$(pwd)

PROJECT=$1;
PROJECT_PATH="${DIR_PATH}/${PROJECT}"

if [ -d "./$PROJECT" ]; then
    echo "Folder exists already [$PROJECT]."
    exit;
fi

echo $PROJECT_PATH

echo "Setting up $PROJECT ..."

KEY="laravel-setup-script-project: ${PROJECT}"

mkdir ${PROJECT}
cd ${PROJECT}

git clone git@github.com:john-needham/laravel-setup.git .

TEMPLATE="__PROJECT__"

# remove setup script from laravel-setup, we dont need it
rm "${PROJECT_PATH}/setup"

sed -i '' "s/${TEMPLATE}/${PROJECT}/g" "${PROJECT_PATH}/docker-compose.yml"
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" "${PROJECT_PATH}/Makefile"
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" "${PROJECT_PATH}/infra/etc/nginx/site.conf"
sed -i '' "s/${TEMPLATE}/${PROJECT}/g" "${PROJECT_PATH}/cmd"

make build
make project tmp=tmp
shopt -s dotglob
mv "${PROJECT_PATH}/tmp/*" "${PROJECT_PATH}/"
rm "${PROJECT_PATH}/tmp"
make run

if grep -q "$KEY" /etc/hosts
then
    echo "Host file already configured"
else
    echo "## laravel-setup-script-project: ${PROJECT}"  | sudo tee -a /etc/hosts
    echo "127.0.0.1 ${PROJECT}.local" | sudo tee -a /etc/hosts
    echo "## laravel-setup-script" | sudo tee -a /etc/hosts
    echo "" | sudo tee -a /etc/hosts
fi

echo "Browse to http://${PROJECT}.local"
